document.getElementById("mybutton").onclick = function(){
var tmp = document.getElementById("text").value;
var tmp2;
var tmp3 =[
'Abgespaced',
'Abgespaced',
'Adrian',
'Aktion',
'Alf',
'Aliens',
'All', 
'Angst',
'Anna',
'Archenhold-Sternwarte',
'Arizona',
'Arm',
'Arme',
'Arme',
'Art',
'Asteroid',
'Asteroid',
'Asteroiden',
'Astronaut',
'Astronaut*innen',
'Astronauten',
'Astronautin',
'Astronom',
'Astronomen',
'Astronomin',
'Astronomie',
'Astrophysikerin',
'Atmosphäre',
'Auftritt',
'Augen',
'Augenabstand',
'Aussehen',
'Außerirdische',
'Bahnen',
'Batterien',
'Barringer',
'Basis',
'Basteleien',
'Batterie',
'Bauer',
'Bedingungen',
'Begriff',
'Beine',
'Beispiel',
'Beispiel',
'Berlin',
'Berliner',
'Besserung',
'Beweis',
'Bewertung',
'Bild',
'Bilder',
'Bildern',
'Bilger',
'Brille',
'Bröckchen',
'Buchstaben',
'Bye',
'Bälle',
'Bücher',
'CHEOPS',
'Celsius',
'Chewbacca',
'Christoph',
'Computer',
'Danke',
'Daumen',
'Deutsch',
'Dingern',
'Dinosaurier',
'Disziplin',
'Durchmesser',
'ET',
'Ecke',
'Ein',
'Eis',
'Eisen',
'Eisen',
'Eisen Diese',
'Eisenmeteoriten',
'Elemente',
'Elliot',
'Ende',
'Endeffekt',
'Energie',
'Englisch',
'Entdeckung',
'Entdeckung',
'Entdeckungen',
'Entfernung',
'Entschuldige',
'Entsperren',
'Er',
'Erdatmosphäre',
'Erde',
'Erdzwilling',
'Ergebnis',
'Erwachsene',
'Exoplaneten',
'Fakt',
'Fall',
'Fan',
'Fehler',
'Fenster',
'Fensterputzer',
'Fensterputzer',
'Fernbedienung',
'Fernrohr',
'Fiction',
'Film',
'Filme',
'Finger',
'Finger',
'Fingern',
'Folge',
'Foto',
'Fragen',
'Freundschaft',
'Früher',
'Gab',
'Gas',
'Gasen',
'Gefühl',
'Gegend',
'Genau',
'Genau',
'Genau Der',
'Geschwindigkeit Wie',
'Gesteins',
'Gesteinsbrocken',
'Gesteinsklumpen',
'Gewicht',
'Glas',
'Glaubst',
'Glück',
'Grad',
'Gradmann',
'Grundsätzlich',
'Größe',
'Haarsternen',
'Hale-Bopp',
'Hallo',
'Hand',
'Handschuhen',
'Haus',
'Hendrik',
'Herzstück',
'Himmelskörper',
'Hobby',
'Hoffnung',
'Hände',
'ISS',
'Idee',
'Infos',
'Inspiration',
'Intelligenz',
'Interaktion',
'Internet',
'Interview',
'Interview',
'Jahre',
'Jonathan',
'Jonathan',
'Julia',
'Juni',
'Junimaximus',
'Juniminimuss',
'Jupiter',
'Justin',
'Justin',
'Justin Dieser',
'Justin',
'Kaffee',
'Kameras',
'Kartoffel',
'Kids',
'Kilo', 
'Kilogramm',
'Kilometer',
'Kilometer',
'Kinder',
'Kinderreporter',
'Klasse',
'Klassen',
'Klingonen',
'Knopf',
'Knopf',
'Kohlenstoff',
'Kollegen',
'Komet',
'Kometen',
'Kommandos',
'Kommt',
'Kopf',
'Krater',
'Krater Genau',
'Kratern',
'Kristin',
'Krümelchen',
'Kuh',
'Können',
'Könnte',
'Körper',
'Kühe',
'Laura',
'Leben',
'Lebensformen',
'Lebewesen',
'Lendl',
'Lieblingsfilm',
'Liftoff', 
'Abgespaced',
'Linde',
'Luft',
'Lufthülle',
'Länder',
'Löcher',
'Löwel ',
'Mal',
'Malt',
'Mars',
'Material',
'Materialien',
'Mechanik',
'Meinung',
'Meinung',
'Meister',
'Mensch',
'Menschen',
'Menschen',
'Metall',
'Meteorit',
'Meteorit',
'Meteoriten',
'Meter',
'Methan',
'Methan',
'Mikroorganismen',
'Milchstraße',
'Milliarden',
'Million',
'Minuten',
'Mischung',
'Mittelfinger',
'Mond',
'Mond',
'Monde',
'Monika',
'Monitor',
'Mork',
'Musik',
'Männchen',
'Nachbar',
'Name',
'Namen',
'Namen',
'Nayla',
'Neugier',
'Not-aus',
'Oberfläche',
'Oberkörper',
'Oberpfaffenhofen',
'Objekte',
'Objekten',
'Organismen',
'Ork',
'Paar',
'Panel',
'Panele',
'Paradies',
'Park',
'Phosphor',
'Planet',
'Planetarien',
'Planetarium',
'Planeten',
'Podcast',
'Podcastteam',
'Position',
'Problem',
'Programm Rolling',
'Psst',
'Putzvorrichtung',
'Raum',
'Raumfahrt',
'Raumstation',
'Referat',
'Reinigen',
'Reporterin',
'Riethammer',
'Roboter',
'Robotern',
'Roboters',
'Roboters',
'Rolling',
'Räder',
'Rädern',
'Sache',
'Sandstürme',
'Satelliten',
'Sauerstoff',
'Schall',
'Schalter',
'Schalter',
'Schaltern',
'Schimpfwörter',
'Schneeball',
'Schrak',
'Schröder',
'Schule',
'Schwefel',
'Schweif',
'Schweif',
'Schweif',
'Schweifstern',
'Science',
'Sehne',
'Sehr',
'Seite',
'Serie',
'Shownotes',
'Sicht',
'Signale',
'Solarpanel',
'Solarpanelen',
'Sollen',
'Sonne',
'Sonnensystem',
'Sonnensystems',
'Sounds',
'Spacy',
'Spacy',
'Spacy‘s',
'Spannung',
'Spock',
'Star',
'Staub',
'Staub',
'Stefan',
'Stern',
'Sternwarte',
'Sternwarten',
'Stickstoff',
'Stiftung',
'Stitch',
'Stoff',
'Stoffe',
'Stoffe',
'Stoffe',
'Studio',
'Stück',
'Tages',
'Tapani',
'Team',
'Technik',
'Teil',
'Teleskop',
'Temperatur',
'Treptower',
'Tschüss',
'Tschüss',
'Tschüss Wenn',
'Ultras',
'Universum',
'Unterschied',
'Unterschied',
'Vanessa',
'Vergleich',
'Verständnis',
'Vorführeffekt',
'Wand Wenn',
'Wars',
'Wars',
'Was',
'Wasser',
'Weil',
'Welt',
'Welt',
'Weltall',
'Weltall Glaubst',
'Weltall',
'Weltraum',
'Wenig',
'Wenn',
'Wesen',
'Willkommen',
'Wissenschaftler*innen',
'Wow',
'Würmer',
'Yoga',
'Zeichen',
'Zeigfinger',
'Zeit',
'Zentrum',
'Zwei',
'Moderatorin',
'Moderator',
'Absorptionslinien',
'Absorptionsspektrum',
'Emissionslinien ',
'Flekkengruppen ',
'Hauptreihe ',
'Hof',
'Kern',
'Kernschatten',
'Kleine',
'Koma',
'Kontinuum ',
'Meteorit ',
'Milchstraßen-System ',
'Ortsmeridian',
'Planet',
'Planeten ;',
'Roten',
'Sarosperiode',
'Schiefe',
'Schweif',
'Sommer-Solstitium',
'Spiralnebel',
'Tierkreiszeichen ',
'Wanderer',
'Weißen',
'Winter-Solstitium',
'Fraunhofer',
'14m24s',
'Sonnenwende ',
'Sonnenwende',
'Sonnenflecken',
'Ablenkung',
'Absorption',
'Abstand',
'Abstände',
'Abständen',
'Aktivitätsgebieten',
'Albedo ',
'Albedos',
'Am',
'Anders',
'Angabe',
'Anlagerung',
'Annäherung',
'Anzahl',
'Aphel Phasenwikel ',
'Art',
'Asteroiden',
'Astronomen',
'Astronomie',
'Astronomischen',
'Atmosphäre',
'Atom',
'Auch',
'Aufspaltung',
'Auge',
'Ausdruck',
'Ausgangspunkt',
'Azimut',
'Bahn',
'Bahnbewegung',
'Bahnen',
'Bedeckung',
'Bedingungen',
'Begegnung',
'Bei',
'Beispiel',
'Beleuchtung',
'Beobachter',
'Beobachter ',
'Beobachters ',
'Beobachtung',
'Bereich',
'Bewegung',
'Beziehung',
'Blickwinkeln',
'Bode-Titiussche',
'Bogensekunde',
'Breite',
'Chromosphäre',
'Coriolis-Effekt',
'Dadurch',
'Das',
'Dauer',
'Definiert',
'Deklination',
'Der',
'Dezember',
'Dichte',
'Die',
'Dieses',
'Differenz',
'Dunkle',
'',
'Durch',
'Ebene',
'Ebene ',
'Eigenschaft',
'Eigenschaften',
'Ein',
'Eine',
'Einer',
'Einfall',
'Einfluß',
'Einheit ',
'Einheiten ',
'Ekliptik',
'Ekliptik ',
'Ekliptik Komet ',
'Elektronen',
'Element',
'Elemente',
'Elements',
'Elongation',
'Emission',
'Energie',
'Energiemenge',
'Entfernung',
'Entfernungsmaß',
'Erdabstand',
'Erdatmosphäre',
'Erdbahn',
'Erdbahn',
'Erdboden',
'Erde',
'Erde Siderische',
'Erde-Mond-Systems',
'Erdoberfläche',
'Erdäquator',
'Erdäquators',
'Extrem',
'Fackeln',
'Feldes',
'Finsternisse',
'Fixsternen',
'Fixsternhimmel;',
'Flares',
'Flecken',
'Fleckengruppen',
'Form',
'Formel',
'Formen',
'Frequenz',
'Frequenz',
'Frequenzbereich',
'Frequenzänderung',
'Frühlingspunkt',
'Frühlingspunktes',
'Fähigkeit',
'Für',
'Galaxis Kulmination ',
'Gas',
'Gase',
'Gebiet',
'Gebiete',
'Gebieten',
'Gebräuchlicher',
'Gegenpunkt',
'Gegenwart',
'Gesamtbetrag',
'Geschoß',
'Gezeitenkräfte',
'Glaskörper',
'Grad',
'Gravitationswirkung',
'Gravitationszentrum',
'Grenze',
'Großes',
'Großkreis',
'Großkreise',
'Größe',
'Größen',
'Gürtel',
'HRD',
'Halbkugel',
'Halbschattens',
'Halo',
'Hauptreihensternen',
'HeII einfach',
'Helium',
'Helle',
'Helles',
'Helligkeit',
'Helligkeit',
'Hilfe',
'Himmel Ion',
'Himmel Rochesche',
'Himmelskoordinaten',
'Himmelskugel',
'Himmelskugel;',
'Himmelskörper',
'Himmelskörpers',
'Himmelsäquator',
'Himmelsäquator;',
'Horizont',
'Horizont',
'Horizont Leuchtkraft',
'Hz Elongation',
'Häufigkeit',
'Höhe',
'Höhe Bahnstörungen',
'Höhe Fackeln',
'Höhe Synchrotronstrahlung',
'Höhe Umbra',
'Hülle',
'Im',
'Imlinden',
'In',
'Infrarot',
'Innern',
'Intervall',
'Ionen',
'Ionosphäre',
'Jahr',
'Jahre',
'Jahren Spektrum',
'Jahres',
'Jedes',
'Juni',
'Jupiter',
'Jupiterbahn Astronomische',
'Knoten Galaxis',
'Koinzidenz Chromosphäre',
'Kometen',
'Kometen;',
'Komponente',
'Konjunktion',
'Konjunktionen',
'Konjunktionen',
'Kontinuum',
'Koordinate',
'Koordinatensystem',
'Korona',
'Kreis',
'Kugel',
'Körper',
'Körper',
'Körpers',
'Körpers',
'Laboratorium',
'Laufe',
'Lebensdauer',
'Leuchtkraft',
'Leuchtkraft Hertzsprung-Russell-Diagramm',
'Leuchtspur Meteorit',
'Licht',
'Licht',
'Lichtgeschwindigkeit',
'Lichtjahr',
'Lichtjahre',
'Lichtjahren',
'Lichtmenge',
'Lichtmenge;',
'Lichtquelle',
'Lichts',
'Linien',
'Linien',
'Linien Sternzeit',
'Luft-',
'Luftmoleküle',
'Länge',
'Magnetfeldern',
'Magnetfelds',
'Mars',
'Marsund',
'Massenmittelpunkt',
'Materie',
'Maß',
'Meeresstrimungen Deklination',
'Meridian',
'Meridiandurchgang',
'Merkur',
'Mesosphäre',
'Messung',
'Meteorite',
'Meteoriten',
'Meteoriteneinschlägen',
'Meteorphänomen',
'Minuten',
'Mitgliedern',
'Mittagsmeridian Meteor',
'Mittel',
'Mittelpunkt',
'Mond',
'Mond',
'Monden',
'Mondes',
'Mondes Tierkreis',
'Mondfinsternis',
'Mondoberfläche',
'Mricorite',
'Möglichkeit',
'Nach',
'Nacht',
'Neben',
'Neigung',
'Neptun',
'Nord-Süd',
'Norden',
'Norden',
'Nordpunkt',
'Oberfläche',
'Obertläche',
'Objekte',
'Objekts',
'Okkultation Bodesche',
'Okkultation Opposition',
'Opposition',
'Ortsveränderung',
'Osten',
'Oszillationen',
'Ozon',
'Parallaxe',
'Parallaxe Parsec',
'Parsec',
'Penumbra Zeeman-Effekt',
'Perihel',
'Perihel Asteroid',
'Periode',
'Periode',
'Periode Solarkonstante',
'Photosphäre',
'Phänomenen',
'Planet',
'Planet',
'Planet-Sonne',
'Planeten',
'Planeten',
'Planeten Exosphäre',
'Planeten Parallaxe',
'innerhalb',
'Planetenatmosphäre',
'Planetenradien Saros',
'Pluto',
'Plötzliche',
'Polarisation',
'Polarisation Quadratur',
'Polarisator',
'Pole',
'Position',
'Positionsangabe',
'Positionsbestimmung',
'Projektion',
'Protonen',
'Prozent',
'Punkt',
'Punkte',
'Punktes',
'Quadratmeter',
'Quelle',
'Quelle;',
'Raum',
'Reaktionen',
'Reflexionsvermögen',
'Regel',
'Region',
'Reihe',
'Rektaszension',
'Rektaszension Doppler-Effekt',
'Relativbewegung',
'Reste',
'Richtung',
'Richtung',
'Riesen',
'Rochesche',
'Rotationsachse',
'Rotationsperiode',
'Röntgenstrahlen',
'Satelliten',
'Saturn',
'Sauerstoff Aphel',
'Schatten',
'Schattenkegel',
'Schattens',
'Scheinbare',
'Schicht',
'Schichten',
'Schnittpunkt',
'Schnittpunkte',
'Schwerpunkt',
'Schwingungen',
'Schwingungsebene',
'Schwingungsebenen',
'Seiten',
'Sekunde',
'Sekunden',
'Sichtbares',
'Siehe',
'Skala',
'So',
'Solstitien',
'Sonne',
'Sonne',
'Sonne;',
'Sonnenaktivität',
'Sonnenatmosphäre',
'SonnenatmosphäreCoriolis-Effekt',
'Sonnenfinsternis',
'SonnenfleckengruppenFinsternis',
'Sonnenstrahlung',
'Sonnensystems',
'Sonnenwindes Kosmische',
'Sonnenzeit',
'Sonnenzyklus Sonnensystem',
'Sotinenflecken',
'Spektralapparats',
'Spektrallinien',
'Spektraltyp',
'Spektren',
'Spektrum',
'Spektrum Schwerpunkt',
'Spezialfall',
'Spiralform',
'Sporadisch',
'Staub',
'Stellt',
'Stellungen',
'Stern',
'Sternbildern',
'Sterne',
'Sternen',
'Sterngruppen',
'Sternhimmel',
'Sterns',
'Sterns',
'Sternsystem',
'Sternzeit',
'Strahlen',
'Strahlung',
'Strahlung',
'Strahlungsausbrüche',
'Strahlungsenergie',
'Stratosphäre Troposphäre ',
'Strecke',
'Stunden',
'Störungen',
'Synodische',
'System',
'System Sonnenwind ',
'Systems',
'Tage',
'Tagen',
'Teil',
'Teilchen',
'Teilchenstrom',
'Teile',
'Temperatur',
'Temperatur',
'Treten',
'Troposphäre',
'Ultraviolett',
'Umbra',
'Umlaufs',
'Umlautbahn',
'Umständen Schwarzer',
'Unpolarisierte',
'Unregelmäßigkeiten',
'Uranus',
'Ursprung',
'Vakuum',
'Venus',
'Venus',
'Verbindungen',
'Verbindungslinie',
'Verbindungslinien',
'Verglühen',
'Verhältnis',
'Verlust',
'Verschwinden',
'Verteilung',
'Violetten',
'Vorgänge',
'Vorkommen',
'Weitgehend',
'Welle',
'Wellen',
'Wellen',
'Wellenlänge',
'Wellenlänge',
'Wellenlängen',
'Wellenlängen Frühlingspunkt',
'Wellenlängen;',
'Werte',
'Werten',
'Winkel',
'Winkelabstand',
'Wirkung',
'Wort',
'Wärme',
'Zahl',
'Zeiteinheit',
'Zeitintervall',
'Zeitmessung',
'Zeitpunkt',
'Zentrum',
'Zielpunkt',
'Zonen',
'Zusammenhang',
'Zwerge',
'Zyklus'
];
	

var tmp_array = tmp.split(" ");

var tmp3_lgth = tmp3.length;

tmp = " "+tmp+" ";

tmp = tmp.replaceAll(" ", "---");
tmp = tmp.replaceAll("\n", "---");

document.getElementById("label").innerHTML = "";
document.getElementById("label").innerHTML += tmp+"\n\n\n<br><br>";

//Planeten Gasriesen Gaalxien
//Stern
//

//Planeten---Gasreisen---Galaxien---Stern---Astern---

for (var i = 0; i < tmp3_lgth; i++)
{
	var substantiv = "---"+tmp3[i]+"---";
	var substklein = substantiv.toLowerCase();	
	tmp = tmp.replaceAll(substklein, substantiv);		
	
	var substantiv = "---"+tmp3[i]+".";
	var substklein = substantiv.toLowerCase();	
	tmp = tmp.replaceAll(substklein, substantiv);		

	var substantiv = "---"+tmp3[i]+",";
	var substklein = substantiv.toLowerCase();	
	tmp = tmp.replaceAll(substklein, substantiv);		

	var substantiv = "---"+tmp3[i]+"!";
	var substklein = substantiv.toLowerCase();	
	tmp = tmp.replaceAll(substklein, substantiv);
	
	var substantiv = "---"+tmp3[i]+"?";
	var substklein = substantiv.toLowerCase();	
	tmp = tmp.replaceAll(substklein, substantiv);

}



tmp = tmp.replaceAll("abgespeist", "Abgespaced");

/*	if(tmp==tmp3[0]|| tmp==tmp3[1]|| tmp==tmp3[2]){
		tmp2='richtig';
	}else {
		tmp2='falsch'
	}
*/
	
tmp = tmp.replaceAll("---", " ");
	document.getElementById("label").innerHTML += tmp;
	
	//document.getElementById("text").value = tmp; 
	
}